name = "rattler-build"
type = "cli"

[resolve]
git-url = "https://github.com/prefix-dev/rattler-build"

[platform.linux]
download-file = "rattler-build-{arch}-unknown-linux-musl"

[platform.macos]
download-file = "rattler-build-{arch}-apple-darwin"

[platform.windows]
download-file = "rattler-build-{arch}-pc-windows-msvc.exe"

[install]
download-url = "https://github.com/prefix-dev/rattler-build/releases/download/v{version}/{download_file}"
unpack = false
