name = "ShellCheck"
type = "cli"

[resolve]
git-url = "https://github.com/koalaman/shellcheck"

[platform.linux]
download-file = "shellcheck-v{version}.linux.{arch}.tar.xz"
archive-prefix = "shellcheck-v{version}"

[platform.macos]
download-file = "shellcheck-v{version}.darwin.{arch}.tar.xz"
archive-prefix = "shellcheck-v{version}"

[platform.windows]
download-file = "shellcheck-v{version}.zip"
archive-prefix = "shellcheck-v{version}"

[install]
download-url = "https://github.com/koalaman/shellcheck/releases/download/v{version}/{download_file}"

[install.arch]
arm = "armv6hf"
