name = "Infisical"
type = "cli"

[resolve]
git-url = "https://github.com/Infisical/infisical"
version-pattern = "^infisical-cli/v((?<major>[0-9]+)\\.(?<minor>[0-9]+)\\.(?<patch>[0-9]+))"

[platform.linux]
download-file = "infisical_{version}_linux_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.macos]
download-file = "infisical_{version}_darwin_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.windows]
download-file = "infisical_{version}_windows_{arch}.zip"
checksum-file = "checksums.txt"

[install]
download-url = "https://github.com/Infisical/infisical/releases/download/infisical-cli/v{version}/{download_file}"
checksum-url = "https://github.com/Infisical/infisical/releases/download/infisical-cli/v{version}/{checksum_file}"

[install.arch]
x86 = "386"
x86_64 = "amd64"
arm = "armv6"
aarch64 = "arm64"