name = "Gum"
type = "cli"

[resolve]
git-url = "https://github.com/charmbracelet/gum"

[platform.linux]
download-file = "gum_{version}_Linux_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.macos]
download-file = "gum_{version}_Darwin_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.windows]
download-file = "gum_{version}_Windows_{arch}.zip"
checksum-file = "checksums.txt"

[install]
download-url = "https://github.com/charmbracelet/gum/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/charmbracelet/gum/releases/download/v{version}/{checksum_file}"

[install.arch]
x86 = "i386"
arm = "armv6"
aarch64 = "arm64"
