name = "just"
type = "cli"

[resolve]
git-url = "https://github.com/casey/just"

[platform.linux]
download-file = "just-{version}-{arch}-unknown-linux-musl.tar.gz"

[platform.macos]
download-file = "just-{version}-{arch}-apple-darwin.tar.gz"

[platform.windows]
download-file = "just-{version}-{arch}-pc-windows-msvc.zip"

[install]
download-url = "https://github.com/casey/just/releases/download/{version}/{download_file}"
