name = "Dagger"
type = "cli"

[resolve]
git-url = "https://github.com/dagger/dagger"
version-pattern = "^v((?<major>[0-9]+)\\.(?<minor>[0-9]+)\\.(?<patch>[0-9]+))"

[platform.linux]
download-file = "dagger_v{version}_linux_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.macos]
download-file = "dagger_v{version}_darwin_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.windows]
download-file = "dagger_v{version}_windows_{arch}.zip"
checksum-file = "checksums.txt"

[install]
download-url = "https://github.com/dagger/dagger/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/dagger/dagger/releases/download/v{version}/{checksum_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"
