name = "Cosign"
type = "cli"

[resolve]
git-url = "https://github.com/sigstore/cosign"

[platform.linux]
download-file = "cosign-linux-{arch}"
checksum-file = "cosign_checksums.txt"

[platform.macos]
download-file = "cosign-darwin-{arch}"
checksum-file = "cosign_checksums.txt"

[platform.windows]
download-file = "cosign-windows-{arch}.exe"
checksum-file = "cosign_checksums.txt"

[install]
download-url = "https://github.com/sigstore/cosign/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/sigstore/cosign/releases/download/v{version}/{checksum_file}"
unpack = false

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"
