name = "CMake"
type = "cli"

[resolve]
git-url = "https://github.com/Kitware/CMake"

[platform.linux]
download-file = "cmake-{version}-linux-{arch}.tar.gz"
checksum-file = "cmake-{version}-SHA-256.txt"
archive-prefix = "cmake-{version}-linux-{arch}"

[platform.macos]
download-file = "cmake-{version}-macos-universal.tar.gz"
checksum-file = "cmake-{version}-SHA-256.txt"
archive-prefix = "cmake-{version}-macos-universal/CMake.app/Contents"

[platform.windows]
download-file = "cmake-{version}-windows-{arch}.zip"
checksum-file = "cmake-{version}-SHA-256.txt"
archive-prefix = "cmake-{version}-windows-{arch}"

[install]
download-url = "https://github.com/Kitware/CMake/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/Kitware/CMake/releases/download/v{version}/{checksum_file}"

[install.arch]
x86 = "i386"

[install.primary]
exe-path = "bin/cmake"

[install.secondary.ccmake]
exe-path = "bin/ccmake"

[install.secondary.cpack]
exe-path = "bin/cpack"

[install.secondary.ctest]
exe-path = "bin/ctest"
