name = "actionlint"
type = "cli"

[resolve]
git-url = "https://github.com/rhysd/actionlint"

[platform.linux]
download-file = "actionlint_{version}_linux_{arch}.tar.gz"
checksum-file = "actionlint_{version}_checksums.txt"

[platform.macos]
download-file = "actionlint_{version}_darwin_{arch}.tar.gz"
checksum-file = "actionlint_{version}_checksums.txt"

[platform.windows]
download-file = "actionlint_{version}_windows_{arch}.zip"
checksum-file = "actionlint_{version}_checksums.txt"

[install]
download-url = "https://github.com/rhysd/actionlint/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/rhysd/actionlint/releases/download/v{version}/{checksum_file}"

[install.arch]
arm = "armv6"
aarch64 = "arm64"
x86 = "386"
x86_64 = "amd64"
